name: "Verify Code"
on:
  push:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: cargo build --verbose

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: lint
        run: cargo clippy --verbose -- -D warnings

  audit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install cargo-audit
        run: cargo install cargo-audit

      - name: audit
        run: cargo audit